---
# tasks file for ansible-role-create-account 
- name: APT | Update
  apt:
    upgrade: dist
    update_cache: yes
- name: Nginx | Install
  apt:
    name: nginx
    state: present
- include_tasks: setup-reverse.yml
  when: nginx_reverse == true
- include_tasks: setup-server.yml
  when: nginx_reverse == false

  