---
- name: Nginx | Install
  apt:
    name: nginx
    state: present
- name: "Nginx | Remove default config"
  file:
    path: "/etc/nginx/nginx.conf"
    state: absent
- name: Nginx | Default config
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
- name: Nginx | Default vhost
  template:
    src: server/default.j2
    dest: "/etc/nginx/sites-enabled/default"
  when: redirect_domain is defined
# - name: "Nginx | Pre Vhost {{ domain }}"
#   template:
#     src: pre-vhost.j2
#     dest: "/etc/nginx/sites-enabled/{{ domain }}"
#    notify: nginx reload

#- import_tasks: letsencrypt.yml
# - name: "Nginx | Vhost {{ domain }}"
#   template:
#     src: vhost.j2
#     dest: "/etc/nginx/sites-enabled/{{ domain }}"
#   notify: nginx reload