- name: "Nginx | Remove default config"
  file:
    path: "/etc/nginx/nginx.conf"
    state: absent
- name: Nginx | Default config
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
- name: Nginx | Install Vhost
  template:
    src: reverse/vhost.j2
    dest: "/etc/nginx/site-available/{{ domain }}"
- name: Nginx | Activate vhost
  file:
    src: "/etc/nginx/site-available/{{ domain }}"
    dst: "/etc/nginx/site-enable/{{ domain }}"
    state: link